// ------------------------------------------------------------------------------
//  <auto-generated>
//      此代码由编码的 UI 测试生成器生成。
//      版本: 14.0.0.0
//
//      如果重新生成代码，则更改此文件可能会导致错误的行为，
//      并将丢失这些更改。
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestProject1
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1 - 使用“RecordedMethod1Params”将参数传递到此方法中。
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinButton uI新标签页Button = this.UICWaitN编写自动化测试czh4869Window.UIItemTabList.UI新标签页Button;
            WinEdit uI地址和搜索栏Edit = this.UICWaitN编写自动化测试czh4869Window.UIItemGroup.UI地址和搜索栏Edit;
            WinControl uIChromeLegacyWindowDocument = this.UICWaitN编写自动化测试czh4869Window.UIChromeLegacyWindowWindow.UIChromeLegacyWindowDocument;
            WinControl uIChromeLegacyWindowDocument1 = this.UICWaitN编写自动化测试czh4869Window.UIChromeLegacyWindowWindow1.UIChromeLegacyWindowDocument;
            WinControl uI百度贴吧全球最大的中文社区GoogleCDocument = this.UICWaitN编写自动化测试czh4869Window.UIChromeLegacyWindowWindow1.UI百度贴吧全球最大的中文社区GoogleCDocument;
            #endregion

            // 单击 “新标签页” 按钮
            Mouse.Click(uI新标签页Button, new Point(31, 15));

            // 在 “地址和搜索栏” 文本框 中键入“www{Enter}”
            Keyboard.SendKeys(uI地址和搜索栏Edit, this.RecordedMethod1Params.UI地址和搜索栏EditSendKeys, ModifierKeys.None);

            // 单击 “Chrome Legacy Window” 文档
            Mouse.Click(uIChromeLegacyWindowDocument, new Point(1569, 16));

            // 单击 “Chrome Legacy Window” 文档
            Mouse.Click(uIChromeLegacyWindowDocument1, new Point(970, 92));

            // 在 “百度贴吧——全球最大的中文社区 - Google Chrome” 文档 中键入“{CapsLock}UFO{Enter}”
            Keyboard.SendKeys(uI百度贴吧全球最大的中文社区GoogleCDocument, this.RecordedMethod1Params.UI百度贴吧全球最大的中文社区GoogleCDocumentSendKeys, ModifierKeys.None);
        }
        
        #region Properties
        public virtual RecordedMethod1Params RecordedMethod1Params
        {
            get
            {
                if ((this.mRecordedMethod1Params == null))
                {
                    this.mRecordedMethod1Params = new RecordedMethod1Params();
                }
                return this.mRecordedMethod1Params;
            }
        }
        
        public UICWaitN编写自动化测试czh4869Window UICWaitN编写自动化测试czh4869Window
        {
            get
            {
                if ((this.mUICWaitN编写自动化测试czh4869Window == null))
                {
                    this.mUICWaitN编写自动化测试czh4869Window = new UICWaitN编写自动化测试czh4869Window();
                }
                return this.mUICWaitN编写自动化测试czh4869Window;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod1Params mRecordedMethod1Params;
        
        private UICWaitN编写自动化测试czh4869Window mUICWaitN编写自动化测试czh4869Window;
        #endregion
    }
    
    /// <summary>
    /// 要传递到“RecordedMethod1”中的参数
    /// </summary>
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class RecordedMethod1Params
    {
        
        #region Fields
        /// <summary>
        /// 在 “地址和搜索栏” 文本框 中键入“www{Enter}”
        /// </summary>
        public string UI地址和搜索栏EditSendKeys = "www{Enter}";
        
        /// <summary>
        /// 在 “百度贴吧——全球最大的中文社区 - Google Chrome” 文档 中键入“{CapsLock}UFO{Enter}”
        /// </summary>
        public string UI百度贴吧全球最大的中文社区GoogleCDocumentSendKeys = "{CapsLock}UFO{Enter}";
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UICWaitN编写自动化测试czh4869Window : WinWindow
    {
        
        public UICWaitN编写自动化测试czh4869Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "c# WaitN编写自动化测试 - czh4869623的专栏 - CSDN博客 - Google Chrome";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "Chrome_WidgetWin_1";
            this.WindowTitles.Add("c# WaitN编写自动化测试 - czh4869623的专栏 - CSDN博客 - Google Chrome");
            this.WindowTitles.Add("新标签页 - Google Chrome");
            this.WindowTitles.Add("百度一下，你就知道 - Google Chrome");
            this.WindowTitles.Add("百度贴吧——全球最大的中文社区 - Google Chrome");
            #endregion
        }
        
        #region Properties
        public UIItemTabList UIItemTabList
        {
            get
            {
                if ((this.mUIItemTabList == null))
                {
                    this.mUIItemTabList = new UIItemTabList(this);
                }
                return this.mUIItemTabList;
            }
        }
        
        public UIItemGroup UIItemGroup
        {
            get
            {
                if ((this.mUIItemGroup == null))
                {
                    this.mUIItemGroup = new UIItemGroup(this);
                }
                return this.mUIItemGroup;
            }
        }
        
        public UIChromeLegacyWindowWindow UIChromeLegacyWindowWindow
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow == null))
                {
                    this.mUIChromeLegacyWindowWindow = new UIChromeLegacyWindowWindow(this);
                }
                return this.mUIChromeLegacyWindowWindow;
            }
        }
        
        public UIChromeLegacyWindowWindow1 UIChromeLegacyWindowWindow1
        {
            get
            {
                if ((this.mUIChromeLegacyWindowWindow1 == null))
                {
                    this.mUIChromeLegacyWindowWindow1 = new UIChromeLegacyWindowWindow1(this);
                }
                return this.mUIChromeLegacyWindowWindow1;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTabList mUIItemTabList;
        
        private UIItemGroup mUIItemGroup;
        
        private UIChromeLegacyWindowWindow mUIChromeLegacyWindowWindow;
        
        private UIChromeLegacyWindowWindow1 mUIChromeLegacyWindowWindow1;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemTabList : WinTabList
    {
        
        public UIItemTabList(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.WindowTitles.Add("c# WaitN编写自动化测试 - czh4869623的专栏 - CSDN博客 - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinButton UI新标签页Button
        {
            get
            {
                if ((this.mUI新标签页Button == null))
                {
                    this.mUI新标签页Button = new WinButton(this);
                    #region 搜索条件
                    this.mUI新标签页Button.SearchProperties[WinButton.PropertyNames.Name] = "新标签页";
                    this.mUI新标签页Button.WindowTitles.Add("c# WaitN编写自动化测试 - czh4869623的专栏 - CSDN博客 - Google Chrome");
                    #endregion
                }
                return this.mUI新标签页Button;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUI新标签页Button;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemGroup : WinGroup
    {
        
        public UIItemGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.WindowTitles.Add("新标签页 - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinEdit UI地址和搜索栏Edit
        {
            get
            {
                if ((this.mUI地址和搜索栏Edit == null))
                {
                    this.mUI地址和搜索栏Edit = new WinEdit(this);
                    #region 搜索条件
                    this.mUI地址和搜索栏Edit.SearchProperties[WinEdit.PropertyNames.Name] = "地址和搜索栏";
                    this.mUI地址和搜索栏Edit.WindowTitles.Add("新标签页 - Google Chrome");
                    #endregion
                }
                return this.mUI地址和搜索栏Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUI地址和搜索栏Edit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow : WinWindow
    {
        
        public UIChromeLegacyWindowWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "605947960";
            this.WindowTitles.Add("百度一下，你就知道 - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region 搜索条件
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("百度一下，你就知道 - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIChromeLegacyWindowWindow1 : WinWindow
    {
        
        public UIChromeLegacyWindowWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "605947192";
            this.WindowTitles.Add("百度贴吧——全球最大的中文社区 - Google Chrome");
            #endregion
        }
        
        #region Properties
        public WinControl UIChromeLegacyWindowDocument
        {
            get
            {
                if ((this.mUIChromeLegacyWindowDocument == null))
                {
                    this.mUIChromeLegacyWindowDocument = new WinControl(this);
                    #region 搜索条件
                    this.mUIChromeLegacyWindowDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUIChromeLegacyWindowDocument.WindowTitles.Add("百度贴吧——全球最大的中文社区 - Google Chrome");
                    #endregion
                }
                return this.mUIChromeLegacyWindowDocument;
            }
        }
        
        public WinControl UI百度贴吧全球最大的中文社区GoogleCDocument
        {
            get
            {
                if ((this.mUI百度贴吧全球最大的中文社区GoogleCDocument == null))
                {
                    this.mUI百度贴吧全球最大的中文社区GoogleCDocument = new WinControl(this);
                    #region 搜索条件
                    this.mUI百度贴吧全球最大的中文社区GoogleCDocument.SearchProperties[UITestControl.PropertyNames.ControlType] = "Document";
                    this.mUI百度贴吧全球最大的中文社区GoogleCDocument.WindowTitles.Add("百度贴吧——全球最大的中文社区 - Google Chrome");
                    #endregion
                }
                return this.mUI百度贴吧全球最大的中文社区GoogleCDocument;
            }
        }
        #endregion
        
        #region Fields
        private WinControl mUIChromeLegacyWindowDocument;
        
        private WinControl mUI百度贴吧全球最大的中文社区GoogleCDocument;
        #endregion
    }
}
